import type { Metadata } from "next";

import { Inter as FontSans } from "next/font/google";

import { cn } from "@/lib/utils";
import SideNav from "./_components/SideNav";
import Sidebar from "@/components/Footer";
import Topbar from "@/components/Topbar";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "react-hot-toast";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Myaimix",
  description: "Get the best Content Generated by ai . ",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider
      attribute="class"
      defaultTheme="system"
      enableSystem
      disableTransitionOnChange
    >
      <SideNav />

      <div className=" lg:ml-64 md:ml-[80px] ml-0">
        <Toaster />

        {children}
      </div>
      <Sidebar />
    </ThemeProvider>
  );
}
